cross: install cmake
Building nydusd failed on linux-riscv64 with:

  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

We need to install cmake to allow cross-rs to build.

Signed-off-by: Peng Tao <bergwolf@hyper.sh>