Storage: fix test case test_chunk_map_corrupted
This test case may sometimes fail, like this:

```
thread 'cache::blobcache::blob_cache_tests::test_chunk_map_corrupted' panicked at 'assertion failed: `(left != right)`
   left: `[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]`,
  right: `[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]`', storage/src/cache/blobcache.rs:2041:9
```

The assertion expects a blob cache read to return an all-zero buffer,
but returning a buffer with non-zero data, because the buffer was
not initialized with 0 when it was allocated, which may lead to
reusing a previous buffer data.

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>