rafs/v6: exit when rafs config have digest_validate configured
Rafs v6 does not take chunk digest, so storage subsystem can't
validate chunk data.

thread 'nydus_storage_worker_0' panicked at 'BlobMetaChunk doesn't support `chunk_id()`', storage/src/meta/mod.rs:740:9
stack backtrace:
thread 'nydus_storage_worker_3' panicked at 'BlobMetaChunk doesn't support `chunk_id()`', storage/src/meta/mod.rs:740:9
thread 'nydus_storage_worker_1' panicked at 'BlobMetaChunk doesn't support `chunk_id()`', storage/src/meta/mod.rs:740:9
   0: std::panicking::begin_panic
   1: <nydus_storage::meta::BlobMetaChunk as nydus_storage::device::BlobChunkInfo>::chunk_id
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:

Signed-off-by: Changewei Ge <gechangwei@bytedance.com>