builder: fix configuration error on chunk dict load
This patch fix the error when enable blob-toc feature with `--chunk-dict`:

```
$ nydus-image create --chunk-dict bootstrap=/path/to/chunk-dict-bootstrap --features blob-toc ...

Error: failed to open bootstrap file "/path/to/chunk-dict-bootstrap"  module=builder
```

The separate chunk dict bootstrap doesn't support blob accessible.

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>