Test: fix clippy check in integration_test_diff_build_with_chunk_dict
error: writing `&Vec<_>` instead of `&[_]` involves one more reference and cannot be used with non-Vec-based slices
  --> tests/diff.rs:27:37
   |
27 | fn create_file(path: &Path, chunks: &Vec<Vec<u8>>) {
   |                                     ^^^^^^^^^^^^^ help: change this to: `&[Vec<u8>]`
   |
   = note: `-D clippy::ptr-arg` implied by `-D clippy::all`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg

error: use of `unwrap_or` followed by a call to `new`
  --> tests/diff.rs:79:9
   |
79 | /         chunk_dict_bootstrap
80 | |             .map(|p| format!("--chunk-dict {}", p.to_str().unwrap()))
81 | |             .unwrap_or(String::new()),
   | |_____________________________________^
   |
   = note: `-D clippy::or-fun-call` implied by `-D clippy::all`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#or_fun_call
help: try this
   |
79 |         chunk_dict_bootstrap
80 |             .map(|p| format!("--chunk-dict {}", p.to_str().unwrap())).unwrap_or_default(),
   |

error: usage of `FromIterator::from_iter`
   --> tests/diff.rs:158:41
    |
158 |       let expected_chunk_dict_bootstrap = HashMap::<_, _>::from_iter(IntoIter::new([
    |  _________________________________________^
159 | |         (
160 | |             PathBuf::from("/file-1"),
161 | |             vec![
...   |
189 | |         (PathBuf::from("/file-7"), vec![]),
190 | |     ]));
    | |_______^
    |
    = note: `-D clippy::from-iter-instead-of-collect` implied by `-D clippy::all`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_iter_instead_of_collect
help: use `.collect()` instead of `::from_iter()`
    |
158 |     let expected_chunk_dict_bootstrap = IntoIter::new([
159 |         (
160 |             PathBuf::from("/file-1"),
161 |             vec![
162 |                 (0, chunk_digests_1[0].clone()),
163 |                 (0, chunk_digests_1[1].clone()),
  ...

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>