nydus-image: fix unpack from specify blob dir
Fix the panic when user specify `--blob-dir` on unpack:

```
$ nydus-image unpack --bootstrap /path/to/bootstrap \
    --blob-dir /path/to/blobs \
    --output /path/to/oci.tar

Error: fail to unpack

Caused by:
    both blob path or blob backend config are not specified
```

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>