Builder: fix panic on multi-layers build
Builder panic on multi-layers build:

```
thread 'main' panicked at 'range end index 4293918793 out of range for slice
of length 1048576', src/bin/nydus-image/core/node.rs:307:39`
```

The `dir_set_v6_offset` method will rewrite the inode size of regular file,
that causes the above issue.

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>