Fix unused import in service_controller
error: unused import: `std::path::Path`
 --> src/bin/nydusd/service_controller.rs:7:5
  |
7 | use std::path::Path;
  |     ^^^^^^^^^^^^^^^
  |

Signed-off-by: Gao Xiang <hsiangkao@linux.alibaba.com>