nydus-image: fix a bug related to clap upgrading
thread 'main' panicked at 'Command create: Argument or group 'estargztoc-ref' specified in 'requires*' for 'blob-id' does not exist', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.18/src/builder/debug_asserts.rs:152:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Signed-off-by: Jiang Liu <gerry@linux.alibaba.com>