storage: drop prefetch task in blocking runtime
Otherwise, tokio is warnning with debug mode program

NOTE: this is just workaround

---
thread 'nydus_storage_worker_3' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.': /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/tokio-1.20.0/src/runtime/blocking/shutdown.rs:51
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/backtrace-0.3.66/src/capture.rs:410:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/log-panics-2.1.0/src/lib.rs:115:29
   2: std::panicking::rust_panic_with_hook
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:702:17
   3: std::panicking::begin_panic::{{closure}}
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:617:9
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:138:18
   5: std::panicking::begin_panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:616:12
   6: tokio::runtime::blocking::shutdown::Receiver::wait
             at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/tokio-1.20.0/src/runtime/blocking/shutdown.rs:51:21
   7: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/tokio-1.20.0/src/runtime/blocking/pool.rs:193:12
   8: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/tokio-1.20.0/src/runtime/blocking/pool.rs:210:9
   9: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:448:1
  10: core::ptr::drop_in_place<tokio::runtime::Runtime>
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ptr/mod.rs:448:1
  11: reqwest::blocking::wait::enter
             at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/reqwest-0.11.11/src/blocking/wait.rs:76:21
  12: reqwest::blocking::wait::timeout
             at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/reqwest-0.11.11/src/blocking/wait.rs:13:5
  13: reqwest::blocking::client::ClientHandle::execute_request
             at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/reqwest-0.11.11/src/blocking/client.rs:1049:17
  14: reqwest::blocking::client::Client::execute
             at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/reqwest-0.11.11/src/blocking/client.rs:902:9
  15: reqwest::blocking::request::RequestBuilder::send
             at /home/gechangwei/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/reqwest-0.11.11/src/blocking/request.rs:563:9
  16: nydus_storage::backend::connection::Connection::call_inner
             at /data00/home/gechangwei/git_repo/nydus-rs/storage/src/backend/connection.rs:382:19
  17: nydus_storage::backend::connection::Connection::call
             at /data00/home/gechangwei/git_repo/nydus-rs/storage/src/backend/connection.rs:297:9
  18: nydus_storage::backend::registry::RegistryReader::request

Signed-off-by: Changwei Ge <gechangwei@bytedance.com>