Nydusd: fix panic on cli boot
```
thread 'main' panicked at 'Non-unique argument name: hybrid-mode is already in use'.
```

The argument `hybrid-mode` is defined twice, which is not legal for clap.

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>