Builder: use anyhow crate to handle error
Use anyhow crate to map any Result to anyhow::Result for
easy idiomatic error handling, and we can attach context to help
troubleshooting the error understand where things went wrong
like this:

```
Error: failed to open parent bootstrap file "/path/to/bootstrap"

Caused by:
    No such file or directory (os error 2)
```

Signed-off-by: Yan Song <imeoer@linux.alibaba.com>